theme:
  name: material
  font:
    text: Nunito
  features:
    - navigation.indexes
    - instant
    - navigation.tabs
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - toc:
      permalink: "⚓︎"
      permalink_title: Anchor link to this section for reference
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: camel
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - roamlinks
  - search
  - awesome-pages
  - literate-nav:
      nav_file: SUMMARY.md
extra_css:
  - stylesheets/extra.css
