name: ci 
on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-roamlinks-plugin==0.2.0
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-localsearch
      - run: mkdocs gh-deploy --force
